### ISSUE TITLE
如何将开题报告修改成中期报告？

### ISSUE THREAD

**Issue by jiunhwang** [mohuangrui/ucasproposal#1]
你好，如何将首页中的开题报告修改成中期报告，谢谢。

**Comment by jiunhwang** [comment]
找到答案了，在ucasthesis.cfg文件里修改

**Comment by geyutang** [comment]
@jiunhwang 请问您是如何修改的，可以给出具体步骤吗？谢谢了！

**Comment by jiunhwang** [comment]
时间太久了，有点模糊，我刚找了原来的文件，应该是可以通过修改ucasproposal.cfg文件即可

**Comment by jiunhwang** [comment]
%%%%% --------------------------------------------------------------------------------
%% Copyright (C) Huangrui Mo <huangrui.mo@gmail.com> 
%% This is free software: you can redistribute it and/or modify it
%% under the terms of the GNU General Public License as published by
%% the Free Software Foundation, either version 3 of the License, or
%% (at your option) any later version.
%%%%% --------------------------------------------------------------------------------
%%
%%%% This is the configuration file of the ucasproposal package.
%%
\ProvidesFile{ucasproposal.cfg}
  [2014/10/01 v1.0 ucasproposal
   configuration file]
%%%%% --------------------------------------------------------------------------------
%%
%%%%******************** Config Chinese Labels in Ctex *******************************
%%
\renewcommand*{\contentsname}{\center 报告提纲}
\renewcommand*{\refname}{参考文献}
%%%%% --------------------------------------------------------------------------------
%%
%%%%********************** Labels in Chinese Titlepage *******************************
%%
\def\UCAS@label@thesis{研究生学位论文中期报告}
\def\UCAS@label@title{报告题目}
\def\UCAS@label@author{学生姓名}
\def\UCAS@label@authorid{学号}
\def\UCAS@label@advisor{指导教师}
\def\UCAS@label@advisortitle{职称}
\def\UCAS@label@degree{学位类别}
\def\UCAS@label@major{学科专业}
\def\UCAS@label@field{研究方向}
\def\UCAS@label@institute{研究所(院系)}
\def\UCAS@label@date{填表日期}
\def\UCAS@label@mark{中国科学院大学制}
%%%%% --------------------------------------------------------------------------------
%%
%%%%********************** Values in Chinese Titlepage *******************************
%%
\def\UCAS@value@schoollogo{}
\def\UCAS@value@title{（报告题目）}
\def\UCAS@value@titlemark{\UCAS@value@title}
\def\UCAS@value@author{（作者姓名）}
\def\UCAS@value@authorid{（作者学号）}
\def\UCAS@value@advisor{（导师姓名）}
\def\UCAS@value@advisortitle{（导师职称）}
\def\UCAS@value@degree{硕士}
\def\UCAS@value@degreetype{理学}
\def\UCAS@value@major{}
\def\UCAS@value@field{}
\def\UCAS@value@institute{中国科学院力学研究所}
\def\UCAS@value@chinesedate{\the\year~年~\ifnum\the\month <10 0\fi\the\month~月}
%%%%% --------------------------------------------------------------------------------
%%
%%%%********************** Configure Structure Elements ******************************
%%
%% section
\def\CTEX@section@format{\zihao{4}\heiti}
%% subsection
\def\CTEX@subsection@format{\zihao{-4}\heiti}
%% subsubsection
\def\CTEX@subsubsection@format{\zihao{-4}\heiti}
%%%%% --------------------------------------------------------------------------------
\endinput
%% End of file
%%%%% --------------------------------------------------------------------------------
