### ISSUE TITLE
如何将每一章的标题移动到左边？

### ISSUE THREAD

**Issue by williamzhao95** [mohuangrui/ucasproposal#10]
![image](https://user-images.githubusercontent.com/18749483/72139227-51151280-33c9-11ea-9824-c38f66a4cebf.png)
发现每一章的标题都是居中的，如果要变到左边应该怎么设置呢

**Comment by williamzhao95** [comment]
![image](https://user-images.githubusercontent.com/18749483/72139270-69852d00-33c9-11ea-9152-a6c5a63e9502.png)

**Comment by mohuangrui** [comment]
https://github.com/mohuangrui/ucasproposal/blob/b661eefaef89522dd995ff85f5e8f19aa0e9553b/Style/ucasproposal.cls#L315

改为：
```Tex
        format = \zihao{4}\sffamily,
```

**Comment by zhichengzhao** [comment]
好的

**Comment by zhichengzhao** [comment]
感谢！

**Comment by williamzhao95** [comment]
万分感谢！

**Comment by williamzhao95** [comment]
![image](https://user-images.githubusercontent.com/18749483/72152265-7152ca80-33e5-11ea-8fa7-4aed18671b0d.png)
标题移动左边之后发现参考文献和目录的本来该居中的也变到了左边该怎么设置呢？我看这个是调整了整个section的样式

**Comment by mohuangrui** [comment]
https://github.com/mohuangrui/ucasproposal/blob/b661eefaef89522dd995ff85f5e8f19aa0e9553b/Style/ucasproposal.cfg#L34

改为

```Tex
\def\ucas@label@ch@tocname{\centerline{报告提纲}}
```

https://github.com/mohuangrui/ucasproposal/blob/b661eefaef89522dd995ff85f5e8f19aa0e9553b/Style/ucasproposal.cfg#L42

改为

```Tex
\def\ucas@label@ch@bibname{\centerline{参考文献}}
```

**Comment by williamzhao95** [comment]
好的感谢！
