### ISSUE TITLE
在overleaf中编译会有一些警示信息

### ISSUE THREAD

**Issue by williamzhao95** [mohuangrui/ucasproposal#11]
我在overleaf中编译发现会出现一些警示的信息不知道这些警示信息是否会影响最后的效果，另外编译出来貌似跟这个项目给的demo有区别比如标题都加粗了
![image](https://user-images.githubusercontent.com/18749483/72141424-cc78c300-33cd-11ea-8492-0124496b78d1.png)
是demo没有更新嘛

**Comment by mohuangrui** [comment]
没有影响，PDF 不更新以免增加 git size

**Comment by williamzhao95** [comment]
好的感谢
