### ISSUE TITLE
无法在texlive2020编译，但可以在2019版本编译

### ISSUE THREAD

**Issue by JinyuanShao** [mohuangrui/ucasproposal#13]
## 检查 / Check

- [x] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [x] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [x] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [x] Windows 7/8/10
  - [x] macOS
  - [ ] Linux

- `TeX 发行版 / Tex Distribution`
  - [x] TeX Live 2020
## 描述问题 / Problem Description

问题描述：
更新texlive2020后无法编译出pdf，而texlive2019可以成功编译。
目测是文献引用的问题，请求帮助。
https://github.com/mohuangrui/ucasthesis/issues/281
上面也是一样的问题，但出错的地方不一样，所以提问请求帮助，感谢
具体问题如下图：

## 日志文件 / .log file

将编译生成的 `.log` 文件拖入下行空白处：
[Thesis.log](https://github.com/mohuangrui/ucasproposal/files/4758247/Thesis.log)

## 问题截图 / Screenshots
将出现的问题或需要实现的效果的 `截图照片` 拖入下行空白处：

![image](https://user-images.githubusercontent.com/37828195/84264519-ecb2d680-ab53-11ea-8f77-fa704dc41f7b.png)

**Comment by mohuangrui** [comment]
对于texlive2020，你需要下载使用最新版的ucasproposal，见 https://github.com/mohuangrui/ucasthesis/issues/223

**Comment by JinyuanShao** [comment]
@mohuangrui 收到，感谢耐心解答，已解决
