### ISSUE TITLE
模板编译报错：Critical Package ctex Error: CTeX fontset `fandol' is unavailable in current [  }]

### ISSUE THREAD

**Issue by TTTJJJWWW** [mohuangrui/ucasproposal#15]
## 检查 / Check

- [X] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [ ] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [ ] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [ ] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [ ] Windows 7/8/10
  - [X] macOS
  - [ ] Linux

- `TeX 发行版 / Tex Distribution`
  - [X] TeX Live 
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description

问题描述：
编译报错
Errors:
/usr/local/texlive/2020/texmf-dist/tex/latex/ctex/fontset/ctex-fontset-fandol.def:113: Critical Package ctex Error: CTeX fontset `fandol' is unavailable in current [  }]

## 日志文件 / .log file

将编译生成的 `.log` 文件拖入下行空白处：
This is pdfTeX, Version 3.14159265-2.6-1.40.21 (TeX Live 2020) (preloaded format=pdflatex 2021.1.14)  16 JAN 2021 17:23
entering extended mode
 restricted \write18 enabled.
 %&-line parsing enabled.
**Thesis.tex
(./Thesis.tex
LaTeX2e <2020-02-02> patch level 5
L3 programming layer <2020-03-06> (./Style/ucasproposal.cls

LaTeX Warning: You have requested document class `Style/ucasproposal',
               but the document class provides `ucasproposal'.

Document Class: ucasproposal 2014/10/01 v1.0 LaTeX document class
(/usr/local/texlive/2020/texmf-dist/tex/latex/ctex/ctexart.cls
(/usr/local/texlive/2020/texmf-dist/tex/latex/l3kernel/expl3.sty
Package: expl3 2020-03-06 L3 programming layer (loader) 

(/usr/local/texlive/2020/texmf-dist/tex/latex/l3backend/l3backend-pdfmode.def
File: l3backend-pdfmode.def 2020-03-12 L3 backend support: PDF mode
\l__kernel_color_stack_int=\count167
\l__pdf_internal_box=\box45
))
Document Class: ctexart 2019/05/29 v2.4.16 Chinese adapter for class article (C
TEX)
(/usr/local/texlive/2020/texmf-dist/tex/latex/l3packages/xparse/xparse.sty
Package: xparse 2020-03-06 L3 Experimental document command parser
\l__xparse_current_arg_int=\count168
\g__xparse_grabber_int=\count169
\l__xparse_m_args_int=\count170
\l__xparse_v_nesting_int=\count171
)
(/usr/local/texlive/2020/texmf-dist/tex/latex/l3packages/l3keys2e/l3keys2e.sty
Package: l3keys2e 2020-03-06 LaTeX2e option processing using LaTeX3 keys
) (/usr/local/texlive/2020/texmf-dist/tex/latex/ctex/ctexhook.sty
Package: ctexhook 2019/05/29 v2.4.16 Document and package hooks (CTEX)
)
(/usr/local/texlive/2020/texmf-dist/tex/latex/ctex/ctexpatch.sty
Package: ctexpatch 2019/05/29 v2.4.16 Patching commands (CTEX)
)
(/usr/local/texlive/2020/texmf-dist/tex/latex/base/fix-cm.sty
Package: fix-cm 2015/01/14 v1.1t fixes to LaTeX

(/usr/local/texlive/2020/texmf-dist/tex/latex/base/ts1enc.def
File: ts1enc.def 2001/06/05 v3.0e (jk/car/fm) Standard LaTeX file
LaTeX Font Info:    Redeclaring font encoding TS1 on input line 47.
))
(/usr/local/texlive/2020/texmf-dist/tex/latex/ms/everysel.sty
Package: everysel 2011/10/28 v1.2 EverySelectfont Package (MS)
)
\l__ctex_tmp_int=\count172
\l__ctex_tmp_box=\box46
\l__ctex_tmp_dim=\dimen134
\g__ctex_section_depth_int=\count173
\g__ctex_font_size_int=\count174

(/usr/local/texlive/2020/texmf-dist/tex/latex/ctex/config/ctexopts.cfg
File: ctexopts.cfg 2019/05/29 v2.4.16 Option configuration file (CTEX)
)
(/usr/local/texlive/2020/texmf-dist/tex/latex/base/article.cls
Document Class: article 2019/12/20 v1.4l Standard LaTeX document class
(/usr/local/texlive/2020/texmf-dist/tex/latex/base/size12.clo
File: size12.clo 2019/12/20 v1.4l Standard LaTeX file (size option)
)
\c@part=\count175
\c@section=\count176
\c@subsection=\count177
\c@subsubsection=\count178
\c@paragraph=\count179
\c@subparagraph=\count180
\c@figure=\count181
\c@table=\count182
\abovecaptionskip=\skip47
\belowcaptionskip=\skip48
\bibindent=\dimen135
)
(/usr/local/texlive/2020/texmf-dist/tex/latex/ctex/engine/ctex-engine-pdftex.de
f
File: ctex-engine-pdftex.def 2019/05/29 v2.4.16 (pdf)LaTeX adapter (CTEX)
 (/usr/local/texlive/2020/texmf-dist/tex/latex/cjk/texinput/CJKutf8.sty
Package: CJKutf8 2015/04/18 4.8.4

(/usr/local/texlive/2020/texmf-dist/tex/generic/iftex/ifpdf.sty
Package: ifpdf 2019/10/25 v3.4 ifpdf legacy package. Use iftex instead.

(/usr/local/texlive/2020/texmf-dist/tex/generic/iftex/iftex.sty
Package: iftex 2020/03/06 v1.0d TeX engine tests
))
(/usr/local/texlive/2020/texmf-dist/tex/latex/base/inputenc.sty
Package: inputenc 2018/08/11 v1.3c Input encoding file
\inpenc@prehook=\toks15
\inpenc@posthook=\toks16
)
......

## 问题截图 / Screenshots
将出现的问题或需要实现的效果的 `截图照片` 拖入下行空白处：

**Comment by TTTJJJWWW** [comment]
@mohuangrui 编译报错求帮助，谢谢！

**Comment by mohuangrui** [comment]
用 xelatex 而不是 pdflatex，后者限制因素较多
