### ISSUE TITLE
请问如何能让 proposal 有类似 thesis 的页眉

### ISSUE THREAD

**Issue by okcd00** [mohuangrui/ucasproposal#16]
## 检查 / Check

- [x] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [ ] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [x] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [ ] Windows 7/8/10
  - [ ] macOS
  - [x] Linux (Overleaf)

- `TeX 发行版 / Tex Distribution`
  - [x] TeX Live 2020 
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description

问题描述：

目前的 UCASProposal 项目编译得到的 PDF 中是没有页眉的。
通过删除 `xhf` 的方式添加页眉后，发现和 UCASThesis 的页眉不同，字体和样式目前都无法满足现在的提交要求      
（要求是和较老版本的一样，偶数页显示“研究生学位论文开题报告”，奇数页显示当前章节名“第X章 xxxxxxx”，均为居中）。        
试图通过修改 `artratex` 文件来实现，但发现 UCASProposal 和 UCASThesis 中的这个文件是完全相同的，页眉的设置也确实是居中 `[C]` 的标题，实际编译的结果确实如下图所示的左右对齐的 section / subsection 名称。     
后来也尝试修改 `.cls` 文件，但也仅能找到如何将 “三” 改为 “第三章” 的位置，所以想请问一下该如何处理页眉，十分感谢！

## 日志文件 / .log file

将编译生成的 `.log` 文件拖入下行空白处：

[output.log](https://github.com/mohuangrui/ucasproposal/files/6590905/output.log)

## 问题截图 / Screenshots
将出现的问题或需要实现的效果的 `截图照片` 拖入下行空白处：

UCASProposal 的页眉

![image](https://user-images.githubusercontent.com/9395067/120629629-95122700-c498-11eb-95c9-af6f7c5518fd.png)

UCASThesis 的页眉

![image](https://user-images.githubusercontent.com/9395067/120629700-abb87e00-c498-11eb-9401-fdffa6645c7c.png)

## 最小工作示例(MWE) / Minimal Working Example 

```Tex
% From
\usepackage[numbers,list, xhf]{Style/artratex}% document settings

% To
\usepackage[numbers,list]{Style/artratex}% document settings
```

**Comment by lxzmads** [comment]
在Thesis.tex里面用`\mainmatter`初始化之后就可以了。

**Comment by okcd00** [comment]
感谢 @lxzmads ！
