### ISSUE TITLE
如果需要增加填表说明那一页，请问该如何增加？

### ISSUE THREAD

**Issue by DennisShaw** [mohuangrui/ucasproposal#17]
## 检查 / Check

- [x] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [x] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [x] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [x] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- `TeX 发行版 / Tex Distribution`
  - [x] TeX Live 
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description

问题描述：
如果需要增加填表说明那一页，请问该如何增加？如何使用定义好的字号来增加填报说明一页？

## 日志文件 / .log file

将编译生成的 `.log` 文件拖入下行空白处：

## 问题截图 / Screenshots
将出现的问题或需要实现的效果的 `截图照片` 拖入下行空白处：

**Comment by HansYeoh** [comment]
请在 Tex/Frontmatter.tex 里面添加，添加位置如下：
![Snipaste_2022-07-18_21-57-08](https://user-images.githubusercontent.com/23377286/179527728-bdc0dc31-43ee-4564-9ad9-337fbde21608.jpg)
