### ISSUE TITLE
题目如何居中？

### ISSUE THREAD

**Issue by holyprince** [mohuangrui/ucasproposal#7]
由于标题比较长但是又没有到换行的长度，不居中应该怎么办呢？谢谢
![pro](https://user-images.githubusercontent.com/4947633/55771492-dece7500-5aba-11e9-8ab8-6d6a6b3b77b1.PNG)

**Comment by mohuangrui** [comment]
请见 https://github.com/mohuangrui/ucasthesis/wiki/常见问题

**Comment by holyprince** [comment]
多谢！使用\hspace*{+3.0em} 可以解决。
