### ISSUE TITLE
编译中出现字体缺失错误

### ISSUE THREAD

**Issue by qwertystar** [mohuangrui/ucasproposal#8]
使用xelatex（texlive套装)编译Thesis.tex时，出现某一字体缺失错误。

fontspec error: "font-not-found" The font "XITSMath-Regular" cannot be found.
出错文件在artratex.sty。

使用Texworks可以编译出来，但是用texstudio编辑器就出不来最终结果。使用pdflatex编译时最终文件可出。不知道这个问题是不是一个需要关注的问题？

**Comment by mohuangrui** [comment]
你好，根据你的测试结果，可能的原因是

1. texstudio 配置异常或错误，导致无法正确索引字体。
2. 你的 texlive 编译器版本过旧或package 不全，缺失理应存在的 XITS 字体。

**Comment by qwertystar** [comment]
> 你好，根据你的测试结果，可能的原因是
> 
> 1. texstudio 配置异常或错误，导致无法正确索引字体。
> 2. 你的 texlive 编译器版本过旧或package 不全，缺失理应存在的 XITS 字体。

您好，根据您提供的信息，我查了一下：
1.我的texlive是2018的，xelatex编辑器版本号XeTeX 3.14159265-2.6-0.99999 (TeX Live 2018/W32TeX)
kpathsea version 6.3.0
2.cmd下敲texdoc XITS ，能正常显示引导文件，在texlive中也找到了对应的文件和文件夹
3.配置异常问题...我查了一下，缺少了几个oft文件，补上就可以正常编译了。
谢谢您。

**Comment by huiwenzhang** [comment]
@qwertystar  请问能具体说说如何修复这个问题的吗，怎么配置texstudio?
