### ISSUE TITLE
无法加载算法模块

### ISSUE THREAD

**Issue by WhiteDLee** [mohuangrui/ucasproposal#9]
1. 关于algorithm命令的包已安装——在ucasthesis-master中能运行
2. package应该已加载，
        artatex.sty中部分命令：
%-> List structures
%-
\ifartx@list% enable enhanced list and verbatim structures
    \RequirePackage{verbatim}% improve verbatim environment
    \RequirePackage{enumitem}% configure the enumerate environment
    \setlist[enumerate]{wide=\parindent}% only indent the first line
    \setlist[itemize]{wide=\parindent}% only indent the first line
    \setlist{nosep}% default text spacing
    \RequirePackage{listings}% source code
    \RequirePackage{algpseudocode,algorithm,algorithmicx}% algorithm
    \providecommand{\algname}{Algorithm}%
    \def\ALG@name{\algname}% rename label
\fi

********************************************分割*******************************************************
运行Thesis.tex模块，提示
! LaTeX Error: Environment algorithm undefined.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.362 \begin{algorithm}
                       [!h]
Your command was ignored.
Type  I <command> <return>  to replace it with another command,
or  <return>  to continue without it.

! Package caption Error: \caption outside float.

See the caption package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.364     \caption
                  {Euclid's algorithm}\label{alg:euclid}
If you do not understand this error, please take a closer look
at the documentation of the `caption' package, especially the
section about errors.
Try typing  <return>  to proceed.
If that doesn't work, type  X <return>  to quit.

! LaTeX Error: Environment algorithmic undefined.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.365     \begin{algorithmic}
                             [1]
Your command was ignored.
Type  I <command> <return>  to replace it with another command,
or  <return>  to continue without it.

! Undefined control sequence.
l.366         \Procedure
                        {Euclid}{$a,b$}\Comment{The g.c.d. of a and b}
The control sequence at the end of the top line
of your error message was never \def'ed. If you have
misspelled it (e.g., `\hobx'), type `I' and the correct
spelling (e.g., `I\hbox'). Otherwise just continue,
and I'll forget about whatever was undefined.

LaTeX Font Info:    Font shape `TU/XITSMath-Regular(2)/m/n' will be
(Font)              scaled to size 7.00075pt on input line 366.
LaTeX Font Info:    Font shape `TU/XITSMath-Regular(2)/m/n' will be
(Font)              scaled to size 5.00053pt on input line 366.
LaTeX Font Info:    Font shape `TU/XITSMath-Regular(3)/m/n' will be
(Font)              scaled to size 6.99925pt on input line 366.
LaTeX Font Info:    Font shape `TU/XITSMath-Regular(3)/m/n' will be
(Font)              scaled to size 4.99947pt on input line 366.
! Undefined control sequence.
l.366         \Procedure{Euclid}{$a,b$}\Comment
                                               {The g.c.d. of a and b}
The control sequence at the end of the top line
of your error message was never \def'ed. If you have
misspelled it (e.g., `\hobx'), type `I' and the correct
spelling (e.g., `I\hbox'). Otherwise just continue,
and I'll forget about whatever was undefined.

! Undefined control sequence.
l.367         \State
                     $r\gets a\bmod b$
The control sequence at the end of the top line
of your error message was never \def'ed. If you have
misspelled it (e.g., `\hobx'), type `I' and the correct
spelling (e.g., `I\hbox'). Otherwise just continue,
and I'll forget about whatever was undefined.

! Undefined control sequence.
l.368         \While
                    {$r\not=0$}\Comment{We have the answer if r is 0}
The control sequence at the end of the top line
of your error message was never \def'ed. If you have
misspelled it (e.g., `\hobx'), type `I' and the correct
spelling (e.g., `I\hbox'). Otherwise just continue,
and I'll forget about whatever was undefined.

! Undefined control sequence.
l.368         \While{$r\not=0$}\Comment
                                       {We have the answer if r is 0}
The control sequence at the end of the top line
of your error message was never \def'ed. If you have
misspelled it (e.g., `\hobx'), type `I' and the correct
spelling (e.g., `I\hbox'). Otherwise just continue,
and I'll forget about whatever was undefined.

! Undefined control sequence.
l.369         \State
                     $a\gets b$
The control sequence at the end of the top line
of your error message was never \def'ed. If you have
misspelled it (e.g., `\hobx'), type `I' and the correct
spelling (e.g., `I\hbox'). Otherwise just continue,
and I'll forget about whatever was undefined.

! Undefined control sequence.
l.370         \State
                     $b\gets r$
The control sequence at the end of the top line
of your error message was never \def'ed. If you have
misspelled it (e.g., `\hobx'), type `I' and the correct
spelling (e.g., `I\hbox'). Otherwise just continue,
and I'll forget about whatever was undefined.

! Undefined control sequence.
l.371         \State
                     $r\gets a\bmod b$
The control sequence at the end of the top line
of your error message was never \def'ed. If you have
misspelled it (e.g., `\hobx'), type `I' and the correct
spelling (e.g., `I\hbox'). Otherwise just continue,
and I'll forget about whatever was undefined.

! Undefined control sequence.
l.372         \EndWhile
                       \label{euclidendwhile}
The control sequence at the end of the top line
of your error message was never \def'ed. If you have
misspelled it (e.g., `\hobx'), type `I' and the correct
spelling (e.g., `I\hbox'). Otherwise just continue,
and I'll forget about whatever was undefined.

! Undefined control sequence.
l.373         \State
                     \textbf{return} $b$\Comment{The gcd is b}
The control sequence at the end of the top line
of your error message was never \def'ed. If you have
misspelled it (e.g., `\hobx'), type `I' and the correct
spelling (e.g., `I\hbox'). Otherwise just continue,
and I'll forget about whatever was undefined.

! Undefined control sequence.
l.373         \State \textbf{return} $b$\Comment
                                                {The gcd is b}
The control sequence at the end of the top line
of your error message was never \def'ed. If you have
misspelled it (e.g., `\hobx'), type `I' and the correct
spelling (e.g., `I\hbox'). Otherwise just continue,
and I'll forget about whatever was undefined.

! Undefined control sequence.
l.374         \EndProcedure
                           
The control sequence at the end of the top line
of your error message was never \def'ed. If you have
misspelled it (e.g., `\hobx'), type `I' and the correct
spelling (e.g., `I\hbox'). Otherwise just continue,
and I'll forget about whatever was undefined.

! LaTeX Error: \begin{document} ended by \end{algorithmic}.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.375     \end{algorithmic}
                           
Your command was ignored.
Type  I <command> <return>  to replace it with another command,
or  <return>  to continue without it.

! LaTeX Error: \begin{document} ended by \end{algorithm}.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.376 \end{algorithm}
                     
Your command was ignored.
Type  I <command> <return>  to replace it with another command,
or  <return>  to continue without it.

**Comment by WhiteDLee** [comment]
这是写在overleaf上的例子：https://www.overleaf.com/3993691431vrtdhstqdgff
仅仅是在原模板上添加了“ucasthesis-master”上关于algorithm的命令。
谢谢！

**Comment by mohuangrui** [comment]
你好，因为那些宏包对非计算机的人大多无用，所以默认并不加载，因此需要在 Thesis.tex 中启用：

```
\usepackage[authoryear,xhf,list]{Style/artratex}% document settings
%- [list]% provide enhanced list environments for algorithm and coding
```

**Comment by mohuangrui** [comment]
等下次更新时，我将默认启用 list 选项，这样还是省事些 ：）

**Comment by WhiteDLee** [comment]
> 你好，因为那些宏包对非计算机的人大多无用，所以默认并不加载，因此需要在 Thesis.tex 中启用：
> 
> ```
> \usepackage[authoryear,xhf,list]{Style/artratex}% document settings
> %- [list]% provide enhanced list environments for algorithm and coding
> ```

完美解决，谢谢了；

**Comment by WhiteDLee** [comment]
> 等下次更新时，我将默认启用 list 选项，这样还是省事些 ：）

还是不太懂LateX的语法，没明白list的作用，哈哈；
谢谢啦！
